version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book-db
  nest-test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - PORT=3000
      - POSTGRESS_URL=postgres://postgres:postgres@postgres:5432/book-db
